/**
 * Onda do Bem — Mock Data
 *
 * Dados mockados para exibição e prototipagem da rede social.
 * Inclui publicações realistas de preservação ambiental em praias e ruas,
 * histórias e comentários com mensagens inspiradoras e de incentivo.
 */

import { PostCategory, type User, type Post, type Comment } from '@/types/entities';

export interface CategoryInfo {
  label: string;
  emoji: string;
  color: string;
}

export const CATEGORY_INFO: Record<PostCategory, CategoryInfo> = {
  [PostCategory.BEACH_CLEANUP]: {
    label: 'Limpeza de Praia',
    emoji: '🌊',
    color: '#0EA5E9',
  },
  [PostCategory.TREE_PLANTING]: {
    label: 'Plantio de Árvores',
    emoji: '🌱',
    color: '#10B981',
  },
  [PostCategory.RECYCLING]: {
    label: 'Reciclagem',
    emoji: '♻️',
    color: '#059669',
  },
  [PostCategory.WATER_CONSERVATION]: {
    label: 'Cuidado com a Água',
    emoji: '💧',
    color: '#38BDF8',
  },
  [PostCategory.COMMUNITY_GARDEN]: {
    label: 'Horta Comunitária',
    emoji: '🥕',
    color: '#F59E0B',
  },
  [PostCategory.ANIMAL_RESCUE]: {
    label: 'Proteção Animal',
    emoji: '🐾',
    color: '#EC4899',
  },
  [PostCategory.DONATION]: {
    label: 'Doação',
    emoji: '❤️',
    color: '#EF4444',
  },
  [PostCategory.EDUCATION]: {
    label: 'Educação Ambiental',
    emoji: '📚',
    color: '#8B5CF6',
  },
  [PostCategory.OTHER]: {
    label: 'Outra Ação',
    emoji: '✨',
    color: '#6366F1',
  },
};

export const CURRENT_USER: User = {
  id: 'user-current',
  email: 'lucas.silva@ondadobem.org',
  username: 'lucas.silva',
  displayName: 'Lucas Silva',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop',
  bio: 'Defensor da natureza e entusiasta de mutirões ecológicos. Criando ondas de impacto positivo todos os dias! 🌊✨',
  location: 'Florianópolis, SC',
  totalActions: 16,
  totalImpact: 420,
  createdAt: '2024-01-10T10:00:00.000Z',
  updatedAt: '2024-05-15T12:00:00.000Z',
};

export interface StoryItem {
  id: string;
  title: string;
  emoji: string;
  authorName: string;
  avatarUrl: string;
}

export const MOCK_STORIES: StoryItem[] = [
  {
    id: 'story-1',
    title: 'Sua Ação',
    emoji: '➕',
    authorName: 'Você',
    avatarUrl: CURRENT_USER.avatarUrl!,
  },
  {
    id: 'story-2',
    title: 'Praia Limpa',
    emoji: '🌊',
    authorName: 'Mariana',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
  },
  {
    id: 'story-3',
    title: 'Copacabana',
    emoji: '🏖️',
    authorName: 'Carolina',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
  },
  {
    id: 'story-4',
    title: 'Pelourinho',
    emoji: '🧹',
    authorName: 'Tiago',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
  },
  {
    id: 'story-5',
    title: 'Remada SP',
    emoji: '🛶',
    authorName: 'Felipe',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
  },
  {
    id: 'story-6',
    title: 'Flores Rua',
    emoji: '🌻',
    authorName: 'Juliana',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop',
  },
  {
    id: 'story-7',
    title: 'Tartaruga',
    emoji: '🐢',
    authorName: 'Dr. André',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-1',
    authorId: 'author-1',
    author: {
      id: 'author-1',
      email: 'mariana.costa@ondadobem.org',
      username: 'mari.ecovida',
      displayName: 'Mariana Costa',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
      bio: 'Bióloga marinha e voluntária.',
      location: 'Ubatuba, SP',
      totalActions: 28,
      totalImpact: 650,
      createdAt: '2023-11-01T08:00:00.000Z',
      updatedAt: '2024-04-10T10:00:00.000Z',
    },
    title: 'Mutirão de Limpeza na Praia do Tenório',
    description:
      'Hoje reunimos mais de 30 voluntários e conseguimos recolher 120kg de resíduos da orla! A maioria era microplástico e tampinhas. O mar agradece cada um que dedicou a manhã de sábado. 🌊🐢',
    category: PostCategory.BEACH_CLEANUP,
    imageUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800&auto=format&fit=crop',
    latitude: -23.4682,
    longitude: -45.0644,
    locationName: 'Praia do Tenório, Ubatuba - SP',
    likesCount: 142,
    commentsCount: 3,
    impactScore: 120,
    isLiked: false,
    comments: [
      {
        id: 'c1-1',
        postId: 'post-1',
        authorId: 'u-c1',
        author: {
          id: 'u-c1',
          displayName: 'Renata Lemos',
          username: 'renata.lemos',
          avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 5,
          totalImpact: 60,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Que orgulho desse grupo! A praia ficou maravilhosa, parabéns a todos os guerreiros! 👏🌊',
        createdAt: '2024-05-28T15:00:00.000Z',
        updatedAt: '2024-05-28T15:00:00.000Z',
      },
      {
        id: 'c1-2',
        postId: 'post-1',
        authorId: 'u-c2',
        author: {
          id: 'u-c2',
          displayName: 'Carlos Eduardo',
          username: 'carlos.edu',
          avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 8,
          totalImpact: 110,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Na próxima edição com certeza vou levar meus filhos para aprenderem essa lição linda! Parabéns! 💙',
        createdAt: '2024-05-28T16:10:00.000Z',
        updatedAt: '2024-05-28T16:10:00.000Z',
      },
      {
        id: 'c1-3',
        postId: 'post-1',
        authorId: 'u-c3',
        author: {
          id: 'u-c3',
          displayName: 'Juliana Castro',
          username: 'ju.castro',
          avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 12,
          totalImpact: 190,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Atitude que inspira o Brasil inteiro! Juntos fazemos a diferença! ✨🐢',
        createdAt: '2024-05-28T17:20:00.000Z',
        updatedAt: '2024-05-28T17:20:00.000Z',
      },
    ],
    createdAt: '2024-05-28T14:30:00.000Z',
    updatedAt: '2024-05-28T14:30:00.000Z',
  },
  {
    id: 'post-6',
    authorId: 'author-6',
    author: {
      id: 'author-6',
      email: 'carolina.mar@ondadobem.org',
      username: 'carol.mar',
      displayName: 'Carolina Meireles',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
      bio: 'Surfista e ativista pelos oceanos limpos.',
      location: 'Rio de Janeiro, RJ',
      totalActions: 38,
      totalImpact: 820,
      createdAt: '2023-08-10T10:00:00.000Z',
      updatedAt: '2024-05-20T10:00:00.000Z',
    },
    title: 'Operação Mar Limpo: 180kg de plástico retirados de Copacabana',
    description:
      'Nossa equipe acordou às 6h da manhã e com a ajuda de banhistas e voluntários locais recolhemos 180kg de lixo plástico, canudos e redes antigas da areia. Cada pedaço retirado é uma vida marinha preservada! 🌊🐢🏖️',
    category: PostCategory.BEACH_CLEANUP,
    imageUrl: 'https://images.unsplash.com/photo-1520116468418-095147820be1?w=800&auto=format&fit=crop',
    latitude: -22.9711,
    longitude: -43.1822,
    locationName: 'Praia de Copacabana, Rio de Janeiro - RJ',
    likesCount: 312,
    commentsCount: 3,
    impactScore: 180,
    isLiked: true,
    comments: [
      {
        id: 'c6-1',
        postId: 'post-6',
        authorId: 'u-c4',
        author: {
          id: 'u-c4',
          displayName: 'Bruno Alencar',
          username: 'bruno.surf',
          avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 9,
          totalImpact: 140,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Trabalho gigante, Carol! Passo aí todo dia correndo e a diferença na areia é surreal. Parabéns guerreiros! 👏💙',
        createdAt: '2024-05-28T09:30:00.000Z',
        updatedAt: '2024-05-28T09:30:00.000Z',
      },
      {
        id: 'c6-2',
        postId: 'post-6',
        authorId: 'u-c5',
        author: {
          id: 'u-c5',
          displayName: 'Aline Rocha',
          username: 'aline.verde',
          avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 14,
          totalImpact: 260,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Na próxima semana contem comigo! Como faço para pegar o kit de luvas e sacos com vocês? 🙌',
        createdAt: '2024-05-28T10:15:00.000Z',
        updatedAt: '2024-05-28T10:15:00.000Z',
      },
      {
        id: 'c6-3',
        postId: 'post-6',
        authorId: 'u-c6',
        author: {
          id: 'u-c6',
          displayName: 'Marcos Vinícius',
          username: 'marcos.vini',
          avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 4,
          totalImpact: 50,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Iniciativas como essa devolvem a esperança na humanidade! Gratidão sem tamanho pelo trabalho de vocês! ✨🌊',
        createdAt: '2024-05-28T11:00:00.000Z',
        updatedAt: '2024-05-28T11:00:00.000Z',
      },
    ],
    createdAt: '2024-05-28T08:00:00.000Z',
    updatedAt: '2024-05-28T08:00:00.000Z',
  },
  {
    id: 'post-7',
    authorId: 'author-7',
    author: {
      id: 'author-7',
      email: 'tiago.cerqueira@ondadobem.org',
      username: 'tiago.comunidade',
      displayName: 'Tiago Cerqueira',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
      bio: 'Líder comunitário no centro histórico de Salvador.',
      location: 'Salvador, BA',
      totalActions: 41,
      totalImpact: 980,
      createdAt: '2023-07-12T09:00:00.000Z',
      updatedAt: '2024-05-18T10:00:00.000Z',
    },
    title: 'Revitalização da Rua das Flores: calçadas varridas e 15 novas lixeiras',
    description:
      'Junto com comerciantes e moradores da rua, fizemos uma grande faxina coletiva! Retiramos entulhos acumulados, lavamos as calçadas históricas e instalamos lixeiras de coleta seletiva coloridas. Cidade limpa é dever de todos nós! 🧹🏛️💛',
    category: PostCategory.RECYCLING,
    imageUrl: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&auto=format&fit=crop',
    latitude: -12.9714,
    longitude: -38.5113,
    locationName: 'Pelourinho, Salvador - BA',
    likesCount: 268,
    commentsCount: 3,
    impactScore: 90,
    isLiked: false,
    comments: [
      {
        id: 'c7-1',
        postId: 'post-7',
        authorId: 'u-c7',
        author: {
          id: 'u-c7',
          displayName: 'Dandara Santana',
          username: 'dandara.s',
          avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 18,
          totalImpact: 320,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Nossa Bahia mais limpa e linda! Orgulho de ver vocês cuidando do nosso patrimônio com tanto amor! 🙌☀️',
        createdAt: '2024-05-27T18:00:00.000Z',
        updatedAt: '2024-05-27T18:00:00.000Z',
      },
      {
        id: 'c7-2',
        postId: 'post-7',
        authorId: 'u-c8',
        author: {
          id: 'u-c8',
          displayName: 'Otávio Ramos',
          username: 'otavio.r',
          avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 7,
          totalImpact: 95,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Amei a ideia das lixeiras! Pequenas ações organizadas que mudam uma comunidade inteira! 👏',
        createdAt: '2024-05-27T19:20:00.000Z',
        updatedAt: '2024-05-27T19:20:00.000Z',
      },
      {
        id: 'c7-3',
        postId: 'post-7',
        authorId: 'u-c9',
        author: {
          id: 'u-c9',
          displayName: 'Clarice Mendes',
          username: 'clarice.m',
          avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 11,
          totalImpact: 175,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Vocês são luz! Parabéns por essa iniciativa maravilhosa. Que sirva de exemplo para outros bairros! ✨',
        createdAt: '2024-05-27T20:00:00.000Z',
        updatedAt: '2024-05-27T20:00:00.000Z',
      },
    ],
    createdAt: '2024-05-27T16:00:00.000Z',
    updatedAt: '2024-05-27T16:00:00.000Z',
  },
  {
    id: 'post-2',
    authorId: 'author-2',
    author: {
      id: 'author-2',
      email: 'gabriel.araujo@ondadobem.org',
      username: 'gabriel.florestas',
      displayName: 'Gabriel Araújo',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
      bio: 'Engenheiro florestal regenerando áreas degradadas.',
      location: 'Curitiba, PR',
      totalActions: 45,
      totalImpact: 1200,
      createdAt: '2023-09-15T09:00:00.000Z',
      updatedAt: '2024-05-01T11:00:00.000Z',
    },
    title: '50 mudas de Araucária plantadas hoje!',
    description:
      'Dia memorável com os alunos da escola municipal! Plantamos 50 mudas nativas em uma área de nascente. Ver as crianças aprendendo a cuidar da terra nos enche de esperança. 🌲💚',
    category: PostCategory.TREE_PLANTING,
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop',
    latitude: -25.4297,
    longitude: -49.2719,
    locationName: 'Parque das Nascentes, Curitiba - PR',
    likesCount: 215,
    commentsCount: 2,
    impactScore: 50,
    isLiked: true,
    comments: [
      {
        id: 'c2-1',
        postId: 'post-2',
        authorId: 'u-c10',
        author: {
          id: 'u-c10',
          displayName: 'Patrícia Gomes',
          username: 'paty.gomes',
          avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 6,
          totalImpact: 80,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Ver as crianças com as mãos na terra é emocionante! Futuro garantido! Parabéns, Gabriel! 🌲🌱',
        createdAt: '2024-05-27T18:00:00.000Z',
        updatedAt: '2024-05-27T18:00:00.000Z',
      },
      {
        id: 'c2-2',
        postId: 'post-2',
        authorId: 'u-c11',
        author: {
          id: 'u-c11',
          displayName: 'Fernando Lima',
          username: 'fe.lima',
          avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 10,
          totalImpact: 150,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Proteger as nascentes é salvar água para as próximas gerações. Belo projeto! 💚💧',
        createdAt: '2024-05-27T19:30:00.000Z',
        updatedAt: '2024-05-27T19:30:00.000Z',
      },
    ],
    createdAt: '2024-05-27T17:15:00.000Z',
    updatedAt: '2024-05-27T17:15:00.000Z',
  },
  {
    id: 'post-8',
    authorId: 'author-8',
    author: {
      id: 'author-8',
      email: 'felipe.zanin@ondadobem.org',
      username: 'felipe.remada',
      displayName: 'Felipe Zanin',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
      bio: 'Remador ecológico e defensor das águas urbanas.',
      location: 'São Paulo, SP',
      totalActions: 33,
      totalImpact: 740,
      createdAt: '2023-10-10T11:00:00.000Z',
      updatedAt: '2024-05-15T14:00:00.000Z',
    },
    title: 'Remada Ecológica: despoluição das margens do Rio Pinheiros',
    description:
      'Descemos de caiaque ao longo de 4km do rio para retirar garrafas PET, pneus e sacolas plásticas presas nas margens. Foram mais de 240kg de materiais retirados e encaminhados para cooperativas! 🛶💦🌿',
    category: PostCategory.WATER_CONSERVATION,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop',
    latitude: -23.5934,
    longitude: -46.6908,
    locationName: 'Parque Linear Bruno Covas, São Paulo - SP',
    likesCount: 289,
    commentsCount: 3,
    impactScore: 240,
    isLiked: false,
    comments: [
      {
        id: 'c8-1',
        postId: 'post-8',
        authorId: 'u-c12',
        author: {
          id: 'u-c12',
          displayName: 'Lorena Dias',
          username: 'lore.dias',
          avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 15,
          totalImpact: 230,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Que atitude espetacular! Praticar esporte e ao mesmo tempo salvar os nossos rios é o combo perfeito! 🛶🌿',
        createdAt: '2024-05-26T18:00:00.000Z',
        updatedAt: '2024-05-26T18:00:00.000Z',
      },
      {
        id: 'c8-2',
        postId: 'post-8',
        authorId: 'u-c13',
        author: {
          id: 'u-c13',
          displayName: 'Gustavo Paes',
          username: 'gu.paes',
          avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 8,
          totalImpact: 120,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Sensacional, Felipe! Tenho caiaque e quero muito me juntar com vocês no próximo final de semana! 👊',
        createdAt: '2024-05-26T19:15:00.000Z',
        updatedAt: '2024-05-26T19:15:00.000Z',
      },
      {
        id: 'c8-3',
        postId: 'post-8',
        authorId: 'u-c14',
        author: {
          id: 'u-c14',
          displayName: 'Vanessa Melo',
          username: 'vane.melo',
          avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 20,
          totalImpact: 350,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'O planeta agradece de coração! Inspiração pura para toda a nossa cidade de São Paulo! ✨',
        createdAt: '2024-05-26T20:30:00.000Z',
        updatedAt: '2024-05-26T20:30:00.000Z',
      },
    ],
    createdAt: '2024-05-26T16:40:00.000Z',
    updatedAt: '2024-05-26T16:40:00.000Z',
  },
  {
    id: 'post-9',
    authorId: 'author-9',
    author: {
      id: 'author-9',
      email: 'juliana.paiva@ondadobem.org',
      username: 'ju.verdeurbano',
      displayName: 'Juliana Paiva',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop',
      bio: 'Arquiteta paisagista e jardineira comunitária.',
      location: 'Belo Horizonte, MG',
      totalActions: 25,
      totalImpact: 510,
      createdAt: '2023-11-20T10:00:00.000Z',
      updatedAt: '2024-05-12T10:00:00.000Z',
    },
    title: 'De terreno baldio a jardim florido: adeus ao lixo na esquina!',
    description:
      'Aquele ponto de descarte clandestino que incomodava a todos na rua virou um lindo canteiro com 60 mudas de girassóis, lavandas e flores nativas. A comunidade se uniu e o resultado é pura vida e cor! 🌻🌿✨',
    category: PostCategory.TREE_PLANTING,
    imageUrl: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&auto=format&fit=crop',
    latitude: -19.9191,
    longitude: -43.9168,
    locationName: 'Bairro Santa Tereza, Belo Horizonte - MG',
    likesCount: 345,
    commentsCount: 3,
    impactScore: 60,
    isLiked: true,
    comments: [
      {
        id: 'c9-1',
        postId: 'post-9',
        authorId: 'u-c15',
        author: {
          id: 'u-c15',
          displayName: 'Letícia Prado',
          username: 'leti.prado',
          avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 11,
          totalImpact: 190,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Moro a duas quadras e passei hoje cedo por aí... que transformação incrível! Minha manhã começou mais leve! 🌻💛',
        createdAt: '2024-05-26T11:00:00.000Z',
        updatedAt: '2024-05-26T11:00:00.000Z',
      },
      {
        id: 'c9-2',
        postId: 'post-9',
        authorId: 'u-c16',
        author: {
          id: 'u-c16',
          displayName: 'Davi Fonseca',
          username: 'davi.f',
          avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 13,
          totalImpact: 210,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Onde havia descaso agora tem vida e esperança! Parabéns pela coragem e dedicação de todos!',
        createdAt: '2024-05-26T12:30:00.000Z',
        updatedAt: '2024-05-26T12:30:00.000Z',
      },
      {
        id: 'c9-3',
        postId: 'post-9',
        authorId: 'u-c17',
        author: {
          id: 'u-c17',
          displayName: 'Sabrina Nogueira',
          username: 'sabrina.n',
          avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 7,
          totalImpact: 115,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Amei demais! Vou passar lá mais tarde para ajudar a regar as plantinhas também! 💚🌱',
        createdAt: '2024-05-26T13:45:00.000Z',
        updatedAt: '2024-05-26T13:45:00.000Z',
      },
    ],
    createdAt: '2024-05-26T09:15:00.000Z',
    updatedAt: '2024-05-26T09:15:00.000Z',
  },
  {
    id: 'post-3',
    authorId: 'author-3',
    author: {
      id: 'author-3',
      email: 'camila.patas@ondadobem.org',
      username: 'camila.resgate',
      displayName: 'Camila Duarte',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
      bio: 'Protetora independente de animais abandonados.',
      location: 'Belo Horizonte, MG',
      totalActions: 32,
      totalImpact: 94,
      createdAt: '2023-12-05T12:00:00.000Z',
      updatedAt: '2024-04-18T14:00:00.000Z',
    },
    title: 'Feira de Adoção: 8 filhotinhos ganharam um lar!',
    description:
      'Nosso domingo não poderia ter sido mais especial! Todos os 8 resgatados da semana passada foram adotados por famílias responsáveis com termo de compromisso e castração agendada. Gratidão imensa! 🐶🐱❤️',
    category: PostCategory.ANIMAL_RESCUE,
    imageUrl: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&auto=format&fit=crop',
    latitude: -19.9167,
    longitude: -43.9345,
    locationName: 'Praça da Liberdade, Belo Horizonte - MG',
    likesCount: 340,
    commentsCount: 2,
    impactScore: 8,
    isLiked: false,
    comments: [
      {
        id: 'c3-1',
        postId: 'post-3',
        authorId: 'u-c24',
        author: {
          id: 'u-c24',
          displayName: 'Renata Lemos',
          username: 'renata.lemos',
          avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 5,
          totalImpact: 60,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Coração quentinho com essa notícia linda! Eles merecem todo o amor do mundo! 🐶❤️',
        createdAt: '2024-05-26T21:00:00.000Z',
        updatedAt: '2024-05-26T21:00:00.000Z',
      },
      {
        id: 'c3-2',
        postId: 'post-3',
        authorId: 'u-c25',
        author: {
          id: 'u-c25',
          displayName: 'Fábio Toledo',
          username: 'fabio.t',
          avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 7,
          totalImpact: 85,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Parabéns pelo trabalho incansável, Camila! Adotar é um ato supremo de amor! 🙌🐾',
        createdAt: '2024-05-26T21:40:00.000Z',
        updatedAt: '2024-05-26T21:40:00.000Z',
      },
    ],
    createdAt: '2024-05-26T20:00:00.000Z',
    updatedAt: '2024-05-26T20:00:00.000Z',
  },
  {
    id: 'post-4',
    authorId: 'author-4',
    author: {
      id: 'author-4',
      email: 'rodrigo.horta@ondadobem.org',
      username: 'rodrigo.verde',
      displayName: 'Rodrigo Mendonça',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
      bio: 'Agroecologia comunitária e compostagem.',
      location: 'São Paulo, SP',
      totalActions: 19,
      totalImpact: 310,
      createdAt: '2024-02-20T10:00:00.000Z',
      updatedAt: '2024-05-10T16:00:00.000Z',
    },
    title: 'Primeira colheita da Horta Solidária do bairro!',
    description:
      'Colhemos alface, tomate, cenoura e ervas frescas cultivadas sem agrotóxicos. Distribuímos mais de 60 cestas agroecológicas para famílias do bairro. Comida de verdade ao alcance de todos! 🥬🥕🍅',
    category: PostCategory.COMMUNITY_GARDEN,
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985b?w=800&auto=format&fit=crop',
    latitude: -23.5505,
    longitude: -46.6333,
    locationName: 'Vila Mariana, São Paulo - SP',
    likesCount: 188,
    commentsCount: 2,
    impactScore: 60,
    isLiked: false,
    comments: [
      {
        id: 'c4-1',
        postId: 'post-4',
        authorId: 'u-c26',
        author: {
          id: 'u-c26',
          displayName: 'Sandra Luz',
          username: 'sandra.luz',
          avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 16,
          totalImpact: 240,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Alimento sem veneno e com amor compartilhado! Essa horta é um tesouro para o bairro! 🥕💚',
        createdAt: '2024-05-25T12:30:00.000Z',
        updatedAt: '2024-05-25T12:30:00.000Z',
      },
      {
        id: 'c4-2',
        postId: 'post-4',
        authorId: 'u-c27',
        author: {
          id: 'u-c27',
          displayName: 'Gustavo Paes',
          username: 'gu.paes',
          avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 8,
          totalImpact: 120,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Muito inspirador, Rodrigo! Quero ajudar no próximo plantio de mudas! Parabéns! 👏🍅',
        createdAt: '2024-05-25T13:00:00.000Z',
        updatedAt: '2024-05-25T13:00:00.000Z',
      },
    ],
    createdAt: '2024-05-25T11:45:00.000Z',
    updatedAt: '2024-05-25T11:45:00.000Z',
  },
  {
    id: 'post-5',
    authorId: 'author-5',
    author: {
      id: 'author-5',
      email: 'beatriz.recicla@ondadobem.org',
      username: 'bia.circular',
      displayName: 'Beatriz Farias',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop',
      bio: 'Economia circular e gestão de resíduos.',
      location: 'Salvador, BA',
      totalActions: 24,
      totalImpact: 580,
      createdAt: '2024-01-05T09:00:00.000Z',
      updatedAt: '2024-05-12T13:00:00.000Z',
    },
    title: 'Ponto de Coleta Seletiva inaugurado no condomínio',
    description:
      'Conseguimos implementar a coleta seletiva para 120 apartamentos! Em apenas 10 dias, já destinamos 250kg de papelão e plástico direto para a cooperativa local de reciclagem. ♻️📦',
    category: PostCategory.RECYCLING,
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop',
    latitude: -12.9777,
    longitude: -38.5016,
    locationName: 'Pituba, Salvador - BA',
    likesCount: 156,
    commentsCount: 2,
    impactScore: 250,
    isLiked: true,
    comments: [
      {
        id: 'c5-1',
        postId: 'post-5',
        authorId: 'u-c28',
        author: {
          id: 'u-c28',
          displayName: 'Mariana Costa',
          username: 'mari.ecovida',
          avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 28,
          totalImpact: 650,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Exemplo prático de que quando a comunidade se organiza, tudo acontece! Parabéns, Bia! ♻️📦👏',
        createdAt: '2024-05-24T10:00:00.000Z',
        updatedAt: '2024-05-24T10:00:00.000Z',
      },
      {
        id: 'c5-2',
        postId: 'post-5',
        authorId: 'u-c29',
        author: {
          id: 'u-c29',
          displayName: 'Davi Fonseca',
          username: 'davi.f',
          avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
          email: '',
          bio: null,
          location: null,
          totalActions: 13,
          totalImpact: 210,
          createdAt: '',
          updatedAt: '',
        },
        parentId: null,
        content: 'Apoiar as cooperativas de catadores é dignidade e sustentabilidade juntas! Brilhante! 🌟',
        createdAt: '2024-05-24T11:15:00.000Z',
        updatedAt: '2024-05-24T11:15:00.000Z',
      },
    ],
    createdAt: '2024-05-24T09:30:00.000Z',
    updatedAt: '2024-05-24T09:30:00.000Z',
  },
];
